version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
